### ISSUE TITLE
关于zhen.csv表格中的结果

### ISSUE THREAD

**Issue by Aureole-1210** [Coldmist-Lu/ErrorAnalysis_Prompt#1]
请问在 zhen.csv 中，score_ChatGPT_EA 是直接与 mqm_avg_score 计算 Kendall，然后得到了论文 Table2 Zh-En Segment ChatGPT-EA 的结果吗？

**Comment by Coldmist-Lu** [comment]
您好，Kendall 系数采用 WMT2022 shared task 中提供的 meta-evaluation 方法 [(Freitag et al., 2022)](https://aclanthology.org/2022.wmt-1.2.pdf)，计算了三种不同类型的 Kendall correlation，最后取平均。具体可见 [Report](https://arxiv.org/pdf/2303.13809.pdf) 2.1 节 Meta-Evaluation 部分。

**Comment by Aureole-1210** [comment]
好的，感谢您的回答～

**Comment by Aureole-1210** [comment]
您好，想确认一下，您是采用了 mt_metrics_eval 中的 stats.py CorrFunction 的计算方式计算三种不同类型('none', 'sys', 'item')的 Kendall correlation，然后取平均嘛？
（我们想要探究一下不同的 prompt 对实验效果的影响，所以想要保证验证方式的一致，但是目前结果不太一致）

**Comment by Coldmist-Lu** [comment]
mtme 包可能只能对整个 WMT 数据集做评估，所以我们复现了那部分代码，将其用在小批量数据集（80 samples）；
由于本文实验时 ChatGPT API 还未开放，实验结果是人工去做的，可能和 API 的输出不太一致，复现出的 correlation 也可能有一些差异；
对于整个 WMT 数据集的评估，由于 API 调用量较大，我们正在和 Tom Kocmi 合作，尽快扩展实验，更新 Report；
关于您说的不同 prompt 对结果的影响，复现或扩展实验中您可能还需要考虑如何批量处理得分，以及处理 ChatGPT 计算不准确的问题。据我们的观察 ChatGPT 出现频率较低，而 GPT-3.5-turbo 出现次数很高，这可能会严重影响最终得分。我们正考虑调整 Prompt 来尽量保证得分准确。
供您参考。感谢您对我们工作的关注！
